Feat/back button
oev-berlin/api-portal pull request #10
Opened 2022-11-29 15:41 UTC by mahmadoev

# Description
Add a return button to the project description page.

2022-11-30 15:43 UTC, tduaniOEV requested changes

2022-11-30 15:43 UTC, tduaniOEV commented on components/Button/interfaces.ts
> +    text:string,
```suggestion
    text:string,
    link: string
```

2022-11-30 15:43 UTC, tduaniOEV commented on components/Button/Button.tsx
> +);
Es macht nicht so viel Sinn, die href fest zu definieren, weil dann die button nicht wiederverwendbar wäre 
```suggestion
export const Button = ({ text, link }:ButtonProps) => (
  <Link href={link}>
    <BackButton variant="contained"> { text } </BackButton>
  </Link>
);

```

2022-11-30 15:43 UTC, tduaniOEV commented on pages/project/[id].tsx
> +      <Button text="Back" />
```suggestion
      <Button text="Back" link="/" />

```

2022-11-30 15:43 UTC, tduaniOEV commented on tests/unit/__tests__/components/Button.test.tsx
> +);
```suggestion
const setupComponent = ({ text, link }: ButtonProps ) => render(
  <Button text={text}  link={link} />,
);

```

2022-12-02 13:46 UTC, duanitamir requested changes
Es gibt noch einige Probleme beim testing
(7 tests fails), und ein Semicolon fellt noch (./components/Button/interfaces.ts)

2022-12-07 09:13 UTC, merged