Feat/add routing to microservices
oev-berlin/api-portal pull request #11
Opened 2022-11-30 14:31 UTC by mahmadoev

2022-11-30 15:37 UTC, tduaniOEV requested changes

2022-11-30 15:37 UTC, tduaniOEV commented on components/Card/fragments/MicroService/interfaces.ts
> +    isMicroservice: boolean,
`isMicroservice` kamm optional sein
Wenn es optional wäre, müssten wir die variable nicht immer geben, und als hätte es false als value
```typescript 
interface MicroServiceProps {
    serviceName: string,
    isMicroservice?: boolean,
}

2022-11-30 15:37 UTC, tduaniOEV commented on pages/project/[id].tsx
> +      <ServicesDisplay title="External Services" services={project?.info.externalservices} isMicroservice={false} />
Wenn wir `isMicroservice` optional definieren würden, dann bräuchten wir `isMicroservice={false}` attribute nicht mehr, also 
```typescript 
<ServicesDisplay title="External Services" services={project?.info.externalservices}/>

2022-11-30 15:37 UTC, tduaniOEV commented on components/ServicesDisplay/interfaces.ts
> +    isMicroservice: boolean,
```typescript 
isMicroservice?: boolean

2022-11-30 15:37 UTC, tduaniOEV commented on components/Card/Card.tsx
> +                            isMicroservice={false}
Wenn wir `isMicroservice` als optional definieren würden, dann bräuchten wir `isMicroservice={false}`
attribute nicht mehr, also
```typescript 
                          <Microservice
                            serviceName={microserviceName}
                            key={microserviceName}/>

2022-11-30 15:47 UTC, tduaniOEV requested changes

2022-11-30 15:47 UTC, tduaniOEV commented on components/Card/fragments/MicroService/interfaces.ts
> +    isMicroservice: boolean,
`isMicroservice` kann optional sein
Wenn es optional wäre, müssten wir die variable nicht immer geben, und als hätte es false als value


```suggestion
    serviceName: string,
    isMicroservice?: boolean,
```

2022-11-30 15:47 UTC, tduaniOEV commented on components/Card/Card.tsx
> +                            isMicroservice={false}
Wenn wir `isMicroservice` als optional definieren würden, dann bräuchten wir `isMicroservice={false}`
attribute nicht mehr, also

```suggestion
                            

```

2022-11-30 15:47 UTC, tduaniOEV commented on components/ServicesDisplay/interfaces.ts
> +    isMicroservice: boolean,
```suggestion
    isMicroservice?: boolean,

```

2022-11-30 15:47 UTC, tduaniOEV commented on pages/project/[id].tsx
> +      <ServicesDisplay title="External Services" services={project?.info.externalservices} isMicroservice={false} />
Wenn wir isMicroservice optional definieren würden, dann bräuchten wir isMicroservice={false} attribute nicht mehr, also
```suggestion
      <ServicesDisplay title="External Services" services={project?.info.externalservices} />

```

2022-12-02 13:52 UTC, duanitamir commented on components/Card/fragments/MicroService/Microservice.tsx
> +}
Duplicated code, ich würde die beide kombinieren

```suggestion
  function handelClick() {
  if(isMicroservice){
    router.push(`/project/${serviceName}`)
    }
  }
    
    return (
      <Grid item xs={12} sm={4} md={6} lg={4}>
        <CardActionArea component={Button} onClick={() => handelClick()}>
          <MicroserviceContainer>
            {serviceName}
          </MicroserviceContainer>
        </CardActionArea>
      </Grid>
    );
  }
}

```

2022-12-02 13:53 UTC, duanitamir requested changes
Duplicated code

2022-12-07 08:50 UTC, tduaniOEV approved these changes

2022-12-07 08:50 UTC, merged